### ISSUE TITLE
Sporadic error: Failed to create Skype for Business application

### ISSUE THREAD

**Issue by e-volusian** [danielboth/SkypeForBusinessClient#2]
Hey, while using the example code in the _Demo_ directory, I am sporadically getting this error:

```
Failed to create Skype for Business application. Error: The specified CGI application
encountered an error and the server terminated the process.
At C:\repositories\SkypeForBusinessClient\Demo\99.ps1:76 char:5
+     Throw "Failed to create Skype for Business application. Error: $_ ...
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (Failed to creat...ed the process.:String)
   [], RuntimeException
    + FullyQualifiedErrorId : Failed to create Skype for Business application. Error: The s
   pecified CGI application encountered an error and the server terminated the process.

```

If I wait an indeterminate amount of time, it will usually work again and then stop at some point. Any idea what the cause might be or how I can go about troubleshooting? 

I know the urls and credentials are correct, because if I give an incorrect password it will 100% of the time come back with _Authentication Failed_ error

**Comment by danielboth** [comment]
Hi, the only thing your error message tells me is that the application created by the module encountered an error on the server and was terminated. Do you have access to the server? If so, could you check the Lync Server application log to see if it logs a more verbose message there?

**Comment by e-volusian** [comment]
Okay, I was hoping this would be a common error with a single known cause. I do not have access to the server or its logs.  

The error only pops up occasionally so I can work around it for now.  Thanks!
